# Generated by Django 4.2.1 on 2023-06-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=9)),
                ('home', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SS', 'świerk srebrny'), ('JK', 'jodła kaukaska')], max_length=2)),
                ('localization', models.CharField(max_length=300)),
                ('prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'zapłacone'), ('2', 'zarezerwowane')], max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_choinki.customer')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_choinki.tree')),
            ],
        ),
    ]
