# Generated by Django 4.2.1 on 2023-08-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_choinki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='home',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(choices=[('SS', 'świerk srebrny'), ('JK', 'jodła kaukaska')], default='SS', max_length=2),
        ),
    ]
