# Generated by Django 4.2.1 on 2023-08-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_choinki', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
