# Generated by Django 4.2.1 on 2023-08-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_choinki', '0004_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tree',
        ),
        migrations.AddField(
            model_name='order',
            name='tree',
            field=models.ManyToManyField(to='main_choinki.tree'),
        ),
    ]
